const frenchLabels = {
  active: 'Actif',
  activity: 'Activité',
  archived: 'Archivé',
  approved: 'Approuvé',
  blocked: 'Bloqué',
  bounced: 'Adresse en erreur',
  cancelled: 'Annulé',
  completed: 'Terminé',
  critical: 'Critique',
  draft: 'Brouillon',
  evaluation: 'Évaluation',
  financial: 'Financier',
  high: 'Élevée',
  inactive: 'Inactif',
  in_progress: 'En cours',
  low: 'Basse',
  medium: 'Moyenne',
  meeting: 'Réunion',
  mission: 'Mission',
  narrative: 'Narratif',
  ongoing: 'En cours',
  on_hold: 'En attente',
  pending: 'En attente d’activation',
  planned: 'Planifié',
  published: 'Publié',
  rejected: 'Rejeté',
  review: 'À valider',
  report: 'Rapport',
  scheduled: 'Planifié',
  sending: 'Envoi en cours',
  sent: 'Envoyé',
  submitted: 'Soumis',
  suspended: 'Bloqué',
  todo: 'À faire',
  training: 'Formation',
  contract: 'Contrat',
  photo: 'Photo',
  workshop: 'Atelier',
  other: 'Autre',
  unsubscribed: 'Désabonné'
};

const options = (values) => values.map((value) => ({ value, label: frenchLabels[value] || value }));

const projectStatuses = options(['draft', 'planned', 'active', 'on_hold', 'completed', 'cancelled']);
const taskStatuses = options(['todo', 'in_progress', 'blocked', 'review', 'completed', 'cancelled']);
const priorities = options(['low', 'medium', 'high', 'critical']);

/**
 * Explicit form definitions for API resources exposed in the internal portal.
 * Keeping this list allow-listed prevents a new database column from silently
 * becoming editable from the browser.
 */
export const resourceForms = {
  users: {
    createLabel: 'Créer un acteur',
    editLabel: 'Modifier l’acteur',
    fields: [
      { name: 'first_name', label: 'Prénom', required: true, autoComplete: 'given-name' },
      { name: 'last_name', label: 'Nom', required: true, autoComplete: 'family-name' },
      { name: 'email', label: 'Adresse e-mail', type: 'email', required: true, autoComplete: 'email' },
      { name: 'phone', label: 'Téléphone', type: 'tel', autoComplete: 'tel' },
      { name: 'job_title', label: 'Fonction' },
      { name: 'status', label: 'Statut', type: 'select', defaultValue: 'active', options: options(['pending', 'active', 'suspended', 'inactive']) },
      { name: 'password', label: 'Mot de passe initial', type: 'password', requiredOnCreate: true, passwordPolicy: true, help: '12 caractères minimum, avec majuscule, minuscule, chiffre et caractère spécial. À la première connexion, l’acteur devra le modifier.', autoComplete: 'new-password' },
      { name: 'role_ids', label: 'Rôle attribué', type: 'role-select', optionSource: 'roles', optionLabel: 'role', help: 'Choisissez le rôle principal de cet acteur.' }
    ]
  },
  roles: {
    createLabel: 'Ajouter un rôle',
    editLabel: 'Modifier le rôle',
    fields: [
      { name: 'code', label: 'Code', autoGenerated: true },
      { name: 'name', label: 'Nom du rôle', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'is_system', label: 'Rôle système (protégé contre la suppression)', type: 'checkbox' },
      { name: 'permission_ids', label: 'Autorisations', type: 'checkbox-grid', optionSource: 'permissions', optionLabel: 'permission', special: true }
    ]
  },
  projects: {
    createLabel: 'Ajouter un projet',
    editLabel: 'Modifier le projet',
    fields: [
      { name: 'reference', label: 'Référence', autoGenerated: true },
      { name: 'name', label: 'Nom du projet', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'objectives', label: 'Objectifs', type: 'textarea' },
      { name: 'status', label: 'Statut', type: 'select', defaultValue: 'draft', options: projectStatuses },
      { name: 'priority', label: 'Priorité', type: 'select', defaultValue: 'medium', options: priorities },
      { name: 'start_date', label: 'Date de début', type: 'date' },
      { name: 'end_date', label: 'Date de fin', type: 'date' },
      { name: 'budget', label: 'Budget', type: 'number', min: 0, step: '0.01' },
      { name: 'currency', label: 'Devise', defaultValue: 'USD', maxLength: 3 },
      { name: 'country', label: 'Pays', defaultValue: 'République démocratique du Congo' },
      { name: 'province', label: 'Province' },
      { name: 'territory', label: 'Territoire / ville' },
      { name: 'locality', label: 'Localité' },
      { name: 'progress_percent', label: 'Avancement (%)', type: 'number', autoCalculated: true },
      { name: 'manager_id', label: 'Responsable', type: 'select', optionSource: 'users', optionLabel: 'user' }
    ]
  },
  tasks: {
    createLabel: 'Ajouter une tâche',
    editLabel: 'Modifier la tâche',
    fields: [
      { name: 'reference', label: 'Référence', autoGenerated: true },
      { name: 'title', label: 'Intitulé', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'status', label: 'Statut', type: 'select', defaultValue: 'todo', options: taskStatuses },
      { name: 'priority', label: 'Priorité', type: 'select', defaultValue: 'medium', options: priorities },
      { name: 'start_date', label: 'Date de début', type: 'date' },
      { name: 'due_date', label: 'Échéance', type: 'date' },
      { name: 'progress_percent', label: 'Avancement (%)', type: 'number', autoCalculated: true },
      { name: 'estimated_hours', label: 'Heures estimées', type: 'number', min: 0, step: '0.25' },
      { name: 'actual_hours', label: 'Heures réalisées', type: 'number', min: 0, step: '0.25' }
    ]
  },
  events: {
    createLabel: 'Ajouter un événement',
    editLabel: 'Modifier l’événement',
    fields: [
      { name: 'project_id', label: 'Projet associé', type: 'select', optionSource: 'projects', optionLabel: 'project', help: 'Facultatif : laissez vide pour un rendez-vous indépendant.' },
      { name: 'title', label: 'Intitulé', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'event_type', label: 'Motif', type: 'select', defaultValue: 'meeting', options: options(['meeting', 'mission', 'training', 'workshop', 'other']) },
      { name: 'status', label: 'Statut', type: 'select', defaultValue: 'scheduled', options: options(['scheduled', 'ongoing', 'completed', 'cancelled']) },
      { name: 'starts_at', label: 'Début', type: 'datetime-local', required: true },
      { name: 'ends_at', label: 'Fin', type: 'datetime-local', required: true },
      { name: 'location', label: 'Lieu' },
      { name: 'meeting_url', label: 'Lien de réunion', type: 'url' },
      { name: 'is_public', label: 'Afficher publiquement', type: 'checkbox' }
    ]
  },
  reports: {
    createLabel: 'Ajouter un rapport',
    editLabel: 'Modifier le rapport',
    fields: [
      { name: 'reference', label: 'Référence', autoGenerated: true },
      { name: 'project_id', label: 'Projet associé', type: 'select', optionSource: 'projects', optionLabel: 'project' },
      { name: 'title', label: 'Titre', required: true },
      { name: 'report_type', label: 'Type de rapport', type: 'select', required: true, defaultValue: 'activity', options: options(['activity', 'financial', 'narrative', 'evaluation', 'other']) },
      { name: 'period_start', label: 'Période — début', type: 'date' },
      { name: 'period_end', label: 'Période — fin', type: 'date' },
      { name: 'summary', label: 'Résumé', type: 'textarea' },
      { name: 'content', label: 'Contenu', type: 'textarea' },
      { name: 'status', label: 'Statut', type: 'select', defaultValue: 'draft', options: options(['draft', 'submitted', 'approved', 'rejected', 'archived']) }
    ]
  },
  articles: {
    createLabel: 'Ajouter un article',
    editLabel: 'Modifier l’article',
    layout: 'article-editor',
    filters: [
      { name: 'status', label: 'Statut', options: options(['draft', 'review', 'published', 'archived']) }
    ],
    fields: [
      { name: 'reference', label: 'Référence', autoGenerated: true },
      { name: 'title', label: 'Titre', required: true, layout: 'full' },
      { name: 'excerpt', label: 'Extrait', type: 'textarea', layout: 'full' },
      { name: 'content', label: 'Contenu', type: 'textarea', required: true, layout: 'full' },
      { name: 'featured_image_file', label: 'Photo principale', type: 'file', accept: 'image/jpeg,image/png,image/webp,image/gif', allowOnEdit: true, layout: 'full', help: 'Choisissez une image depuis cet appareil. Elle sera associée à la publication.' },
      { name: 'attachment_files', label: 'Pièces jointes PDF ou Word', type: 'file', accept: '.pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document', allowOnEdit: true, multiple: true, layout: 'full', help: 'Facultatif : sélectionnez un ou plusieurs documents à proposer en téléchargement avec cet article.' },
      { name: 'category_id', label: 'Catégorie', type: 'select', optionSource: 'articleCategories', optionLabel: 'category', layout: 'half' },
      { name: 'status', label: 'Statut', type: 'select', defaultValue: 'draft', options: options(['draft', 'review', 'published', 'archived']), layout: 'half' },
      { name: 'is_featured', label: 'Mettre en avant', type: 'checkbox', layout: 'half' },
      { name: 'published_at', label: 'Date de publication', type: 'datetime-local', layout: 'half' },
      { name: 'slug', label: 'Identifiant URL (slug)', autoGenerated: true }
    ]
  },
  newsletter: {
    createLabel: 'Créer une newsletter',
    editLabel: 'Modifier la newsletter',
    fields: [
      { name: 'subject', label: 'Objet', required: true },
      { name: 'preview_text', label: 'Texte d’aperçu' },
      { name: 'content', label: 'Contenu', type: 'textarea', required: true },
      { name: 'status', label: 'Statut', type: 'select', defaultValue: 'draft', options: options(['draft', 'scheduled', 'sending', 'sent', 'cancelled']) },
      { name: 'scheduled_at', label: 'Date planifiée', type: 'datetime-local' }
    ]
  },
  'newsletter/subscribers': {
    editLabel: 'Modifier l’abonné',
    fields: [
      { name: 'email', label: 'Adresse e-mail', type: 'email', required: true },
      { name: 'first_name', label: 'Prénom' },
      { name: 'last_name', label: 'Nom' },
      { name: 'status', label: 'Statut', type: 'select', defaultValue: 'active', options: options(['active', 'unsubscribed', 'bounced']) },
      { name: 'source', label: 'Source' }
    ]
  },
  media: {
    createLabel: 'Téléverser un média',
    editLabel: 'Modifier le média',
    uploadEndpoint: 'media/upload',
    fields: [
      { name: 'file', label: 'Image ou PDF', type: 'file', requiredOnCreate: true, accept: 'image/jpeg,image/png,image/webp,image/gif,application/pdf' },
      { name: 'article_id', label: 'Article associé', type: 'select', optionSource: 'articles', optionLabel: 'article' },
      { name: 'title', label: 'Titre' },
      { name: 'alt_text', label: 'Texte alternatif' }
    ]
  },
  documents: {
    createLabel: 'Téléverser un document',
    editLabel: 'Modifier le document',
    uploadEndpoint: 'documents/upload',
    fields: [
      { name: 'file', label: 'Fichier', type: 'file', requiredOnCreate: true, accept: 'image/jpeg,image/png,image/webp,image/gif,application/pdf,.doc,.docx,.xls,.xlsx' },
      { name: 'project_id', label: 'Projet associé', type: 'select', optionSource: 'projects', optionLabel: 'project' },
      { name: 'task_id', label: 'Tâche associée', type: 'select', optionSource: 'tasks', optionLabel: 'task' },
      { name: 'title', label: 'Titre' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'document_type', label: 'Type de document', type: 'select', defaultValue: 'other', options: options(['report', 'contract', 'photo', 'other']) },
      { name: 'version_number', label: 'Version', type: 'number', min: 1, step: '1', defaultValue: 1 },
      { name: 'is_public', label: 'Autoriser la diffusion externe', type: 'checkbox' }
    ]
  }
};

export const getResourceForm = (resource) => resourceForms[resource] || null;
