CREATE TABLE IF NOT EXISTS user_avatar_images (
  user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  public_key CHAR(36) NOT NULL UNIQUE,
  mime_type VARCHAR(40) NOT NULL,
  content MEDIUMBLOB NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_avatar_images_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS media_file_contents (
  media_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  public_key CHAR(36) NOT NULL UNIQUE,
  content MEDIUMBLOB NOT NULL,
  CONSTRAINT fk_media_file_contents_media FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE
) ENGINE=InnoDB;
